name: Build python wheels

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Setup pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel

      - name: Build wheel
        run: python -m cibuildwheel --output-dir dist/
        env:
          CIBW_BUILD: cp311-*
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BEFORE_ALL: "yum install -y openblas-devel python3.11-libs python3.11-devel"
          CIBW_BEFORE_BUILD: "ls -R /opt/python/cp311-cp311"

      #- uses: actions/upload-artifact@v2
      #  with:
      #    path: ./dist/*.whl
