name: Build python wheels - macos

on:
  workflow_dispatch

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13]
    steps:
      - uses: actions/checkout@v2
      
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0
        with:
          output-dir: dist
        env:
          CIBW_BUILD: cp312-macosx_x86_64
          CIBW_SKIP: "*win32 *i686 *musllinux*"
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BEFORE_ALL_LINUX: "yum install -y openblas-devel"
          CIBW_BEFORE_ALL_MACOS: "brew install libomp"
          CIBW_CONFIG_SETTINGS: "cmake.define.ENABLE_PYTHON_EMBED=OFF"
          CIBW_ENVIRONMENT_MACOS: "OpenMP_ROOT=$(brew --prefix)/opt/libomp"
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: >
            cd {package} &&
            pytest python/test

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/
          
  pypi-publish:
    runs-on: ubuntu-latest

    needs:
      - build-wheels

    permissions:
      id-token: write

    # Dedicated environments with protections for publishing are strongly recommended.
    environment:
      name: pypi
      url: https://pypi.org/project/pygenten/

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
         skip-existing: true
